name             "httperf"
maintainer       "Joshua Mervine"
maintainer_email "joshua@mervine.net"
license          "MIT"
description      "Installs/Configures httperf"
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
recipe           "httperf::default", "Builds httperf from github.com/rubyops/httperf source."
version          "0.1.1"
depends          "build-essential"
depends          "git"
